[package]
name = "docs-site"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.0", features = [ "sqlx-sqlite", "runtime-async-std-native-tls", "macros" ] }

[dependencies.sea-orm]
version = "1.1.0"
features = ["debug-print"]